apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  # - multicluster-engine.yaml
  # - jfrog-artifactory-jcr.yaml
  # - nexus.yaml
  # - jenkins.yaml
  # - acs.yaml
  - tpa.yaml
